version: '3'
services:
  web:
    build: .
    ports:
      - "7001:8000"
    environment:
      DEEPL_API_KEY: 09623770-cdcb-12f9-c7b1-db3a3b9d088a:fx
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./redis_data
